### ISSUE TITLE
Lost Planet 1 Support

### ISSUE THREAD

**Issue by Drift-King** [LuBuCake/MTF.SoundTool#3]
Sound files for Lost Planet use an older version, however it can still be loaded once you hex-edit the byte after SPAC. The version is 03, but if the data is changed to 04 it is completely loaded as it should be. I do not know if replacement of audio works as intended in-game (haven't tried), but extraction works.

**Comment by LuBuCake** [comment]
Interesting, could you provide me a sample? If that's the case then i can easily add the version to be supported.

**Comment by Drift-King** [comment]
[LP1 HM4200_VOICE.zip](https://github.com/LuBuCake/MTF.SoundTool/files/8680250/LP1.HM4200_VOICE.zip)
I've included sqr and srd files that were grouped with the sound file.

**Comment by LuBuCake** [comment]
The tool now supports Lost Planet's version, also i think you've noticed that the sounds are accelerated just like they are in Resident Evil 6, so you should work around that when importing custom sounds into the game. Last thing, i've rechecked it's FWSE structure and it seems to be the exact same as RE5's so following my instructions listed at the original topic (RE5's one) should get you going just fine with those files.

Now since i don't own a copy of the game, if you could report back if everything is working after you do your thing, then i can mark this one as "done".

**Comment by Drift-King** [comment]
Hmm well its hard to really say that is working properly in-game because of two things, 1 is lack of arc/spc creation requirements for Lost Planet, and 2 it crashing saying it cannot read the file (after attempting to re-create the arc file with ARCtool). If anything i'd just call it here, support is more than enough. The other files in the game are named with a .spac extension and its the same thing as LP's .spc files. Thanks again :)

**Comment by LuBuCake** [comment]
By the logic the tool load/edits/saves the archive which is identical to RE5's SPAC and FWSE structure, it should work just fine in game, the problem probably lies with the decompression or compression of arc files, i've never heard that ARCTool was designed to support this game but since its the same as RE5, using the "pc-re5.bat" that comes with it to unpack and repack its arcs should be your best bet.
